/*
** EPITECH PROJECT, 2020
** PSU_strace_2019
** File description:
** strace
*/

#ifndef SYSCALL_H_
#define SYSCALL_H_

typedef enum type_e {
    DEFAULT,
    INT,
    POINTER,
    STRING,
    STRUCT,
    LONG,
    ULONG,
    SIZE_T,
    SSIZE_T,
    NONE
} type_t;

typedef struct syscall_s {
    char *str;
    type_t arg1;
    type_t arg2;
    type_t arg3;
    type_t arg4;
    type_t arg5;
    type_t arg6;
    size_t nb_arg;
    type_t t_return;
} syscall_t;

static const syscall_t sys[] = {
    {"read", INT, DEFAULT, SIZE_T,
        NONE, NONE, NONE, 3, SSIZE_T},
    {"write", INT, STRING, SIZE_T,
        NONE, NONE, NONE, 3, SSIZE_T},
    {"open", STRING, INT, INT, NONE, NONE, NONE, 3, INT},
    {"close", INT, NONE, NONE,
        NONE, NONE, NONE, 1, INT},
    {"stat", STRING, DEFAULT, NONE,
        NONE, NONE, NONE, 2, INT},
    {"fstat", INT, STRUCT, NONE,
        NONE, NONE, NONE, 2, INT},
    {"lstat", STRING, DEFAULT, NONE,
        NONE, NONE, NONE, 2, INT},
    {"poll", DEFAULT, DEFAULT, DEFAULT,
        NONE, NONE, NONE, 3, INT},
    {"lseek", INT, ULONG, DEFAULT,
        NONE, NONE, NONE, 3, INT},
    {"mmap", POINTER, SIZE_T, INT,
        STRUCT, INT, ULONG, 6, POINTER},
    {"mprotect", POINTER, SIZE_T, INT,
        NONE, NONE, NONE, 3, INT},
    {"munmap", POINTER, SIZE_T, NONE,
        NONE, NONE, NONE, 2, INT},
    {"brk", ULONG, NONE, NONE,
        NONE, NONE, NONE, 1, POINTER},
    {"rt_sigaction", INT, DEFAULT, DEFAULT,
        SIZE_T, NONE, NONE, 4, DEFAULT},
    {"rt_sigprocmask", DEFAULT, DEFAULT, DEFAULT,
        SIZE_T, NONE, NONE, 4, DEFAULT},
    {"rt_sigreturn", NONE, NONE, NONE,
        NONE, NONE, NONE, 0, INT},
    {"ioctl", SIZE_T, SIZE_T, DEFAULT,
        NONE, NONE, NONE, 3, DEFAULT},
    {"pread64", INT, STRING, SIZE_T,
        SIZE_T, NONE, NONE, 4, DEFAULT},
    {"pwrite64", INT, STRING, SIZE_T,
        SIZE_T, NONE, NONE, 4, DEFAULT},
    {"readv", INT, DEFAULT, INT,
        NONE, NONE, NONE, 3, DEFAULT},
    {"writev", INT, DEFAULT, DEFAULT,
        NONE, NONE, NONE, 3, DEFAULT},
    {"access", STRING, INT, NONE,
        NONE, NONE, NONE, 2, INT},
    {"pipe", DEFAULT, NONE, NONE,
        NONE, NONE, NONE, 1, INT},
    {"select", INT, DEFAULT, DEFAULT,
        DEFAULT, DEFAULT, NONE, 5, DEFAULT},
    {"sched_yield", NONE, NONE, NONE,
        NONE, NONE, NONE, 0, DEFAULT},
    {"mremap", DEFAULT, SIZE_T, SIZE_T,
        INT, DEFAULT, NONE, 5, DEFAULT},
    {"msync", POINTER, SIZE_T, INT,
        NONE, NONE, NONE, 3, DEFAULT},
    {"mincore", POINTER, SIZE_T, DEFAULT,
        NONE, NONE, NONE, 3, DEFAULT},
    {"madvise", POINTER, SIZE_T, INT,
        NONE, NONE, NONE, 3, DEFAULT},
    {"shmget", SIZE_T, SIZE_T, INT,
        NONE, NONE, NONE, 3, DEFAULT},
    {"shmat", INT, STRING, INT,
        NONE, NONE, NONE, 3, DEFAULT},
    {"shmctl", DEFAULT, DEFAULT, DEFAULT,
        NONE, NONE, NONE, 3, DEFAULT},
    {"dup", DEFAULT, NONE, NONE,
        NONE, NONE, NONE, 1, DEFAULT},
    {"dup2", INT, INT , NONE,
        NONE, NONE, NONE, 2, INT},
    {"pause", NONE, NONE, NONE,
        NONE, NONE, NONE, 0, DEFAULT},
    {"nanosleep", DEFAULT, DEFAULT, NONE,
        NONE, NONE, NONE, 2, DEFAULT},
    {"getitimer", INT, DEFAULT, NONE,
        NONE, NONE, NONE, 2, DEFAULT},
    {"alarm", DEFAULT, NONE, NONE,
        NONE, NONE, NONE, 1, DEFAULT},
    {"setitimer", DEFAULT, DEFAULT, DEFAULT,
        NONE, NONE, NONE, 3, DEFAULT},
    {"getpid", NONE, NONE, NONE,
        NONE, NONE, NONE, 0, DEFAULT},
    {"sendfile", INT, INT, ULONG,
        SIZE_T, NONE, NONE, 4, SSIZE_T},
    {"socket", INT, INT, INT,
        NONE, NONE, NONE, 3, INT},
    {"connect", INT, DEFAULT, INT,
        NONE, NONE, NONE, 3, DEFAULT},
    {"accept", INT, DEFAULT, INT,
        NONE, NONE, NONE, 3, DEFAULT},
    {"sendto", INT, DEFAULT, SIZE_T,
        SIZE_T, POINTER, DEFAULT, 6, DEFAULT},
    {"recvfrom", INT, DEFAULT, SIZE_T,
        INT, POINTER, INT, 6, DEFAULT},
    {"sendmsg", INT, DEFAULT, INT,
        NONE, NONE, NONE, 3, DEFAULT},
    {"recvmsg", INT, DEFAULT, INT,
        NONE, NONE, NONE, 3, DEFAULT},
    {"shutdown", INT, INT, NONE,
        NONE, NONE, NONE, 2, DEFAULT},
    {"bind", INT, DEFAULT, INT,
        NONE, NONE, NONE, 3, DEFAULT},
    {"listen", INT, INT, NONE,
        NONE, NONE, NONE, 2, INT},
    {"getsockname", INT, DEFAULT, DEFAULT,
        NONE, NONE, NONE, 3, DEFAULT},
    {"getpeername", INT, DEFAULT, DEFAULT,
        NONE, NONE, NONE, 3, DEFAULT},
    {"socketpair", INT, INT , INT,
        POINTER, NONE, NONE, 4, DEFAULT},
    {"setsockopt", INT, INT , INT,
        STRING, INT, NONE, 5, DEFAULT},
    {"getsockopt", INT, INT, INT,
        STRING, POINTER, NONE, 5, DEFAULT},
    {"clone", INT, INT, POINTER,
        POINTER, DEFAULT, NONE, 5, DEFAULT},
    {"fork", NONE, NONE, NONE,
        NONE, NONE, NONE, 0, DEFAULT},
    {"vfork", NONE, NONE, NONE, NONE, NONE, NONE, 0, DEFAULT},
    {"execve", STRING, DEFAULT, DEFAULT,
        NONE, NONE, NONE, 3, DEFAULT},
    {"exit", INT, NONE, NONE,
        NONE, NONE, NONE, 1, NONE},
    {"wait4", SIZE_T, POINTER, INT, DEFAULT,
        NONE, NONE, 4, DEFAULT},
    {"kill", SIZE_T, INT, NONE,
        NONE, NONE, NONE, 2, DEFAULT},
    {"uname", STRING, NONE, NONE,
        NONE, NONE, NONE, 1, DEFAULT},
    {"semget", SIZE_T, INT , INT,
        NONE, NONE, NONE, 3, DEFAULT},
    {"semop", INT, DEFAULT, SIZE_T, NONE,
        NONE, NONE, 3, DEFAULT},
    {"semctl", INT , INT, INT,
        POINTER, NONE, NONE, 4, DEFAULT},
    {"shmdt", STRING, NONE, NONE,
        NONE, NONE, NONE, 1, DEFAULT},
    {"msgget", SIZE_T, INT, NONE,
        NONE, NONE, NONE, 2, DEFAULT},
    {"msgsnd", INT, DEFAULT, SIZE_T,
        INT, NONE, NONE, 4, DEFAULT},
    {"msgrcv", INT, DEFAULT, SIZE_T,
        LONG, INT, NONE, 5, DEFAULT},
    {"msgctl", INT, INT, DEFAULT,
        NONE, NONE, NONE, 3, DEFAULT},
    {"fcntl", SIZE_T, SIZE_T, INT,
        NONE, NONE, NONE, 3, DEFAULT},
    {"flock", SIZE_T, SIZE_T, NONE,
        NONE, NONE, NONE, 2, DEFAULT},
    {"fsync", SIZE_T, NONE, NONE,
        NONE, NONE, NONE, 1, DEFAULT},
    {"fdatasync", SIZE_T, NONE, NONE,
        NONE, NONE, NONE, 1, DEFAULT},
    {"truncate", STRING, LONG, NONE,
        NONE, NONE, NONE, 2, DEFAULT},
    {"ftruncate", SIZE_T, INT, NONE,
        NONE, NONE, NONE, 2, DEFAULT},
    {"getdents", SIZE_T, DEFAULT, SIZE_T,
        NONE, NONE, NONE, 3, DEFAULT},
    {"getcwd", STRING, INT, NONE,
        NONE, NONE, NONE, 2, DEFAULT},
    {"chdir", STRING, NONE, NONE,
        NONE, NONE, NONE, 1, DEFAULT},
    {"fchdir", SIZE_T, NONE, NONE,
        NONE, NONE, NONE, 1, DEFAULT},
    {"rename", STRING, STRING, NONE,
        NONE, NONE, NONE, 2, DEFAULT},
    {"mkdir", STRING, INT, NONE,
        NONE, NONE, NONE, 2, DEFAULT},
    {"rmdir", STRING, NONE, NONE,
        NONE, NONE, NONE, 1, DEFAULT},
    {"creat", STRING, INT , NONE,
        NONE, NONE, NONE, 2, DEFAULT},
    {"link", STRING, STRING, NONE,
        NONE, NONE, NONE, 2, DEFAULT},
    {"unlink", STRING, NONE, NONE,
        NONE, NONE, NONE, 1, DEFAULT},
    {"symlink", STRING, STRING, NONE,
        NONE, NONE, NONE, 2, DEFAULT},
    {"readlink", STRING, STRING, INT,
        NONE, NONE, NONE, 3, DEFAULT},
    {"chmod", STRING, SIZE_T, NONE,
        NONE, NONE, NONE, 2, DEFAULT},
    {"fchmod", SIZE_T, SIZE_T, NONE, NONE,
        NONE, NONE, 2, DEFAULT},
    {"chown", STRING, SIZE_T, SIZE_T,
        NONE, NONE, NONE, 3, DEFAULT},
    {"fchown", SIZE_T, SIZE_T, SIZE_T,
        NONE, NONE, NONE, 3, DEFAULT},
    {"lchown", STRING, SIZE_T, SIZE_T,
        NONE, NONE, NONE, 3, DEFAULT},
    {"umask", INT, NONE, NONE, NONE,
        NONE, NONE, 1, DEFAULT},
    {"gettimeofday", DEFAULT, DEFAULT, NONE,
        NONE, NONE, NONE, 2, DEFAULT},
    {"getrlimit", SIZE_T, DEFAULT, NONE,
        NONE, NONE, NONE, 2, DEFAULT},
    {"getrusage", INT, DEFAULT, NONE,
        NONE, NONE, NONE, 2, DEFAULT},
    {"sysinfo", DEFAULT, NONE, NONE,
        NONE, NONE, NONE, 1, DEFAULT},
    {"times", DEFAULT, NONE, NONE,
        NONE, NONE, NONE, 1, DEFAULT},
    {"ptrace", LONG, LONG, SIZE_T,
        SIZE_T, NONE, NONE, 4, DEFAULT},
    {"getuid", NONE, NONE, NONE,
        NONE, NONE, NONE, 0, DEFAULT},
    {"syslog", INT, STRING, INT,
        NONE, NONE, NONE, 3, DEFAULT},
    {"getgid", NONE, NONE, NONE,
        NONE, NONE, NONE, 0, DEFAULT},
    {"setuid", SIZE_T, NONE, NONE,
        NONE, NONE, NONE, 1, DEFAULT},
    {"setgid", SIZE_T, NONE,
        NONE, NONE, NONE, NONE, 1, DEFAULT},
    {"geteuid", NONE, NONE, NONE,
        NONE, NONE, NONE, 0, DEFAULT},
    {"getegid", NONE, NONE, NONE,
        NONE, NONE, NONE, 0, DEFAULT},
    {"setpgid", SIZE_T, SIZE_T, NONE,
        NONE, NONE, NONE, 2, DEFAULT},
    {"getppid", NONE, NONE, NONE,
        NONE, NONE, NONE, 0, DEFAULT},
    {"getpgrp", NONE, NONE, NONE,
        NONE, NONE, NONE, 0, DEFAULT},
    {"setsid", NONE, NONE, NONE,
        NONE, NONE, NONE, 0, DEFAULT},
    {"setreuid", SIZE_T, SIZE_T, NONE,
        NONE, NONE, NONE, 2, DEFAULT},
    {"setregid", SIZE_T, SIZE_T, NONE,
        NONE, NONE, NONE, 2, DEFAULT},
    {"getgroups", INT, POINTER, NONE,
        NONE, NONE, NONE, 2, DEFAULT},
    {"setgroups", INT, SIZE_T, NONE,
        NONE, NONE, NONE, 2, DEFAULT},
    {"setresuid", POINTER, POINTER, POINTER,
        NONE, NONE, NONE, 3, DEFAULT},
    {"getresuid", POINTER, POINTER, POINTER,
        NONE, NONE, NONE, 3, DEFAULT},
    {"setresgid", SIZE_T, SIZE_T, SIZE_T,
        NONE, NONE, NONE, 3, DEFAULT},
    {"getresgid", POINTER, POINTER, POINTER,
        NONE, NONE, NONE, 3, DEFAULT},
    {"getpgid", SIZE_T, NONE, NONE,
        NONE, NONE, NONE, 1, DEFAULT},
    {"setfsuid", SIZE_T, NONE, NONE,
        NONE, NONE, NONE, 1, DEFAULT},
    {"setfsgid", SIZE_T, NONE, NONE,
        NONE, NONE, NONE, 1, DEFAULT},
    {"getsid", SIZE_T, NONE, NONE,
        NONE, NONE, NONE, 1, DEFAULT},
    {"capget", DEFAULT, DEFAULT, NONE, NONE, NONE, NONE, 2, DEFAULT},
    {"capset", DEFAULT, DEFAULT, NONE, NONE, NONE, NONE, 2, DEFAULT},
    {"rt_sigpending", SIZE_T, SIZE_T, NONE, NONE, NONE, NONE, 2, DEFAULT},
    {"rt_sigtimedwait", POINTER, POINTER, DEFAULT, SIZE_T, NONE, NONE, 4,
        DEFAULT},
    {"rt_sigqueueinfo", SIZE_T, INT, POINTER, NONE, NONE, NONE, 3, DEFAULT},
    {"rt_sigsuspend", POINTER, SIZE_T, NONE, NONE, NONE, NONE, 2, DEFAULT},
    {"sigaltstack", POINTER, POINTER, NONE, NONE, NONE, NONE, 2, DEFAULT},
    {"utime", STRING, DEFAULT, NONE, NONE, NONE, NONE, 2, DEFAULT},
    {"mknod", STRING, SIZE_T, SIZE_T, NONE, NONE, NONE, 3, DEFAULT},
    {"uselib", SIZE_T, NONE, NONE, NONE, NONE, NONE, 1, DEFAULT},
    {"personality", SIZE_T, NONE, NONE, NONE, NONE, NONE, 1, DEFAULT},
    {"ustat", SIZE_T, DEFAULT, NONE, NONE, NONE, NONE, 2, DEFAULT},
    {"statfs", STRING, DEFAULT, NONE, NONE, NONE, NONE, 2, DEFAULT},
    {"fstatfs", SIZE_T, DEFAULT, NONE, NONE, NONE, NONE, 2, DEFAULT},
    {"sysfs", INT, INT, INT, NONE, NONE, NONE, 3, DEFAULT},
    {"getpriority", INT, INT, NONE, NONE, NONE, NONE, 2, DEFAULT},
    {"setpriority", INT, INT, INT, NONE, NONE, NONE, 3, DEFAULT},
    {"sched_setparam", SIZE_T, DEFAULT, NONE, NONE, NONE, NONE, 2, DEFAULT},
    {"sched_getparam", SIZE_T, DEFAULT, NONE, NONE, NONE, NONE, 2, DEFAULT},
    {"sched_setscheduler", INT, INT, DEFAULT, NONE, NONE, NONE, 3, DEFAULT},
    {"sched_getscheduler", SIZE_T, NONE, NONE, NONE, NONE, NONE, 1, DEFAULT},
    {"sched_get_priority_max", INT, NONE, NONE, NONE, NONE, NONE, 1, DEFAULT},
    {"sched_get_priority_min", INT, NONE, NONE, NONE, NONE, NONE, 1, DEFAULT},
    {"sched_rr_get_interval", SIZE_T, DEFAULT, NONE, NONE, NONE, NONE, 2,
        DEFAULT},
    {"mlock", INT, SIZE_T, NONE, NONE, NONE, NONE, 2, DEFAULT},
    {"munlock", INT, SIZE_T, NONE, NONE, NONE, NONE, 2, DEFAULT},
    {"mlockall", INT, NONE, NONE, NONE, NONE, NONE, 1, DEFAULT},
    {"munlockall", NONE, NONE, NONE, NONE, NONE, NONE, 0, DEFAULT},
    {"vhangup", NONE, NONE, NONE, NONE, NONE, NONE, 0, DEFAULT},
    {"modify_ldt", INT, POINTER, INT, NONE, NONE, NONE, 3, DEFAULT},
    {"pivot_root", STRING, STRING, NONE, NONE, NONE, NONE, 2, DEFAULT},
    {"_sysctl", DEFAULT, NONE, NONE, NONE, NONE, NONE, 1, DEFAULT},
    {"prctl", INT, INT, INT, INT, NONE, SIZE_T, 5, DEFAULT},
    {"arch_prctl", DEFAULT, DEFAULT, DEFAULT, NONE, NONE, NONE, 3, DEFAULT},
    {"adjtimex", DEFAULT, NONE, NONE, NONE, NONE, NONE, 1, DEFAULT},
    {"setrlimit", SIZE_T, DEFAULT, NONE, NONE, NONE, NONE, 2, DEFAULT},
    {"chroot", STRING, NONE, NONE, NONE, NONE, NONE, 1, DEFAULT},
    {"sync", NONE, NONE, NONE, NONE, NONE, NONE, 0, DEFAULT},
    {"acct", STRING, NONE, NONE, NONE, NONE, NONE, 1, DEFAULT},
    {"settimeofday", DEFAULT, DEFAULT, NONE, NONE, NONE, NONE, 2, DEFAULT},
    {"mount", STRING, STRING, STRING, SIZE_T, POINTER, NONE, 5, DEFAULT},
    {"umount2", STRING, INT, NONE, NONE, NONE, NONE, 2, DEFAULT},
    {"swapon", STRING, INT, NONE, NONE, NONE, NONE, 2, DEFAULT},
    {"swapNONE", STRING, NONE, NONE, NONE, NONE, NONE, 1, DEFAULT},
    {"reboot", INT, INT , SIZE_T, POINTER, NONE, NONE, 4, DEFAULT},
    {"sethostname", STRING, INT, NONE, NONE, NONE, NONE, 2, DEFAULT},
    {"setdomainname", STRING, INT, NONE, NONE, NONE, NONE, 2, DEFAULT},
    {"iopl", INT, DEFAULT, NONE, NONE, NONE, NONE, 2, DEFAULT},
    {"ioperm", SIZE_T, SIZE_T, INT, NONE, NONE, NONE, 3, DEFAULT},
    {"create_module", INT, INT, NONE, NONE, NONE, NONE, 2, DEFAULT},
    {"init_module", POINTER, INT, STRING, NONE, NONE, NONE, 3, DEFAULT},
    {"delete_module", STRING, SIZE_T, NONE, NONE, NONE, NONE, 2, DEFAULT},
    {"get_kernel_syms", NONE, NONE, NONE, NONE, NONE, NONE, 1, DEFAULT},
    {"query_module", SIZE_T, SIZE_T, SIZE_T,
        SIZE_T, SIZE_T, NONE, 5, DEFAULT},
    {"quotactl", SIZE_T, STRING, SIZE_T, POINTER, NONE, NONE, 4, DEFAULT},
    {"nfsservctl", SIZE_T, SIZE_T, SIZE_T, NONE, NONE, NONE, 3, DEFAULT},
    {"getpmsg", SIZE_T, SIZE_T, SIZE_T, SIZE_T,
        SIZE_T, NONE, 5, DEFAULT},
    {"putpmsg", SIZE_T, SIZE_T, SIZE_T,
        SIZE_T, SIZE_T, NONE, 5, DEFAULT},
    {"afs_syscall", SIZE_T, SIZE_T, SIZE_T,
        SIZE_T, SIZE_T, NONE, 5, DEFAULT},
    {"tuxcall", SIZE_T, SIZE_T, SIZE_T, NONE, NONE, NONE, 3, DEFAULT},
    {"security", SIZE_T, SIZE_T, SIZE_T, NONE, NONE, NONE, 3, DEFAULT},
    {"gettid", NONE, NONE, NONE, NONE, NONE, NONE, 0, DEFAULT},
    {"readahead", INT, SIZE_T, SIZE_T, NONE, NONE, NONE, 3, DEFAULT},
    {"setxattr", STRING, STRING, POINTER, SIZE_T, INT, NONE, 5, DEFAULT},
    {"lsetxattr", STRING, STRING, POINTER, SIZE_T, INT, NONE, 5, DEFAULT},
    {"fsetxattr", INT, STRING, POINTER, SIZE_T, INT, NONE, 5, DEFAULT},
    {"getxattr", STRING, STRING, POINTER, SIZE_T, NONE, NONE, 4, DEFAULT},
    {"lgetxattr", STRING, STRING, POINTER, SIZE_T, NONE, NONE, 4, DEFAULT},
    {"fgetxattr", INT, STRING, POINTER, SIZE_T, NONE, NONE, 4, DEFAULT},
    {"listxattr", STRING, STRING, SIZE_T, NONE, NONE, NONE, 3, DEFAULT},
    {"llistxattr", STRING, STRING, SIZE_T, NONE, NONE, NONE, 3, DEFAULT},
    {"flistxattr", INT, STRING, SIZE_T, NONE, NONE, NONE, 3, DEFAULT},
    {"removexattr", STRING, STRING, NONE, NONE, NONE, NONE, 2, DEFAULT},
    {"lremovexattr", STRING, STRING, NONE, NONE, NONE, NONE, 2, DEFAULT},
    {"fremovexattr", INT, STRING, NONE, NONE, NONE, NONE, 2, DEFAULT},
    {"tkill", SIZE_T, INT, NONE, NONE, NONE, NONE, 2, DEFAULT},
    {"time", POINTER, NONE, NONE, NONE, NONE, NONE, 1, DEFAULT},
    {"futex", POINTER, INT , SIZE_T, DEFAULT, POINTER, SIZE_T, 6, DEFAULT},
    {"sched_setaffinity", SIZE_T, SIZE_T, POINTER, NONE, NONE, NONE, 3,
        DEFAULT},
    {"sched_getaffinity", SIZE_T, SIZE_T, POINTER, NONE, NONE, NONE, 3,
        DEFAULT},
    {"set_thread_area", SIZE_T, NONE, NONE, NONE, NONE, NONE, 1, DEFAULT},
    {"io_setup", SIZE_T, DEFAULT, NONE, NONE, NONE, NONE, 2, DEFAULT},
    {"io_destroy", SIZE_T, NONE, NONE, NONE, NONE, NONE, 1, DEFAULT},
    {"io_getevents", POINTER, LONG, LONG, DEFAULT, NONE, NONE, 4, DEFAULT},
    {"io_submit", POINTER, LONG, DEFAULT, NONE, NONE, NONE, 3, DEFAULT},
    {"io_cancel", POINTER, DEFAULT, DEFAULT, NONE, NONE, NONE, 3, DEFAULT},
    {"get_thread_area", SIZE_T, NONE, NONE, NONE, NONE, NONE, 1, DEFAULT},
    {"lookup_dcookie", SIZE_T, LONG, LONG, NONE, NONE, NONE, 3, DEFAULT},
    {"epoll_create", INT, NONE, NONE, NONE, NONE, NONE, 1, DEFAULT},
    {"epoll_ctl_old", SIZE_T, SIZE_T, SIZE_T,
        SIZE_T, NONE, NONE, 4, DEFAULT},
    {"epoll_wait_old", SIZE_T, SIZE_T, SIZE_T,
        SIZE_T, NONE, NONE, 4, DEFAULT},
    {"remap_file_pages", INT, INT, INT,
        INT, INT, NONE, 5, DEFAULT},
    {"getdents64", SIZE_T, DEFAULT, SIZE_T, NONE, NONE, NONE, 3, DEFAULT},
    {"set_tid_address", POINTER, NONE, NONE, NONE, NONE, NONE, 1, DEFAULT},
    {"restart_syscall", NONE, NONE, NONE, NONE, NONE, NONE, 0, DEFAULT},
    {"semtimedop", INT, DEFAULT, SIZE_T, DEFAULT, NONE, NONE, 4, DEFAULT},
    {"fadvise64", INT, SIZE_T, SIZE_T, INT, NONE, NONE, 4, DEFAULT},
    {"timer_create", SIZE_T, DEFAULT, POINTER, NONE, NONE, NONE, 3, DEFAULT},
    {"timer_settime", SIZE_T, INT, DEFAULT, DEFAULT, NONE, NONE, 4, DEFAULT},
    {"timer_gettime", SIZE_T, DEFAULT, NONE, NONE, NONE, NONE, 2, DEFAULT},
    {"timer_getoverrun", SIZE_T, NONE, NONE, NONE, NONE, NONE, 1, DEFAULT},
    {"timer_delete", SIZE_T, NONE, NONE, NONE, NONE, NONE, 1, DEFAULT},
    {"clock_settime", SIZE_T, DEFAULT, NONE, NONE, NONE, NONE, 2, DEFAULT},
    {"clock_gettime", SIZE_T, DEFAULT, NONE, NONE, NONE, NONE, 2, DEFAULT},
    {"clock_getres", SIZE_T, DEFAULT, NONE, NONE, NONE, NONE, 2, DEFAULT},
    {"clock_nanosleep", SIZE_T, INT, DEFAULT, DEFAULT, NONE, NONE, 4, DEFAULT},
    {"exit_group", INT, NONE, NONE, NONE, NONE, NONE, 1, NONE},
    {"epoll_wait", INT, DEFAULT, INT , INT, NONE, NONE, 4, DEFAULT},
    {"epoll_ctl", INT, INT, INT, DEFAULT, NONE, NONE, 4, DEFAULT},
    {"tgkill", SIZE_T, SIZE_T, INT, NONE, NONE, NONE, 3, DEFAULT},
    {"utimes", STRING, DEFAULT, NONE, NONE, NONE, NONE, 2, DEFAULT},
    {"vserver", SIZE_T, SIZE_T, SIZE_T, SIZE_T, SIZE_T, NONE, 5, DEFAULT},
    {"mbind", SIZE_T, SIZE_T, INT, POINTER,
        INT, SIZE_T, 6, DEFAULT},
    {"set_mempolicy", POINTER, INT, INT, NONE, NONE, NONE, 3, DEFAULT},
    {"get_mempolicy", POINTER, POINTER, INT,
        INT, INT, NONE, 5, DEFAULT},
    {"mq_open", STRING, INT, SIZE_T, DEFAULT, NONE, NONE, 4, DEFAULT},
    {"mq_unlink", STRING, NONE, NONE, NONE, NONE, NONE, 1, DEFAULT},
    {"mq_timedsend", SIZE_T, STRING, SIZE_T, SIZE_T, DEFAULT, NONE, 5, DEFAULT},
    {"mq_timedreceive", SIZE_T, STRING, SIZE_T,
        SIZE_T, DEFAULT, NONE, 5, DEFAULT},
    {"mq_notify", SIZE_T, DEFAULT, NONE, NONE, NONE, NONE, 2, DEFAULT},
    {"mq_getsetattr", SIZE_T, DEFAULT, DEFAULT, NONE, NONE, NONE, 3, DEFAULT},
    {"kexec_load", INT, INT, DEFAULT,
        INT, NONE, NONE, 4, DEFAULT},
    {"waitid", INT, SIZE_T, DEFAULT, INT, DEFAULT, NONE, 5, DEFAULT},
    {"add_key", STRING, STRING, STRING, SIZE_T, NONE, NONE, 4, DEFAULT},
    {"request_key", STRING, STRING, STRING, SIZE_T, NONE, NONE, 4, DEFAULT},
    {"keyctl", INT, INT, INT, INT,
        INT, NONE, 5, DEFAULT},
    {"ioprio_set", INT, INT, INT, NONE, NONE, NONE, 3, DEFAULT},
    {"ioprio_get", INT, INT, NONE, NONE, NONE, NONE, 2, DEFAULT},
    {"inotify_init", NONE, NONE, NONE, NONE, NONE, NONE, 0, DEFAULT},
    {"inotify_add_watch", INT, STRING, SIZE_T, NONE, NONE, NONE, 3, DEFAULT},
    {"inotify_rm_watch", INT, SIZE_T, NONE, NONE, NONE, NONE, 2, DEFAULT},
    {"migrate_pages", SIZE_T, INT, POINTER, POINTER,
        NONE, NONE, 4, DEFAULT},
    {"openat", INT, STRING, INT, INT, NONE, NONE, 4, DEFAULT},
    {"mkdirat", INT, STRING, INT, NONE, NONE, NONE, 3, DEFAULT},
    {"mknodat", INT, STRING, INT, SIZE_T, NONE, NONE, 4, DEFAULT},
    {"fchownat", INT, STRING, SIZE_T, SIZE_T, INT, NONE, 5, DEFAULT},
    {"futimesat", INT, STRING, DEFAULT, NONE, NONE, NONE, 3, DEFAULT},
    {"newfstatat", INT, STRING, DEFAULT, INT, NONE, NONE, 4, DEFAULT},
    {"unlinkat", INT, STRING, INT, NONE, NONE, NONE, 3, DEFAULT},
    {"renameat", INT, STRING, INT, STRING, NONE, NONE, 4, DEFAULT},
    {"linkat", INT, STRING, INT, STRING, INT, NONE, 5, DEFAULT},
    {"symlinkat", STRING, INT, STRING, NONE, NONE, NONE, 3, DEFAULT},
    {"readlinkat", INT, STRING, STRING, INT, NONE, NONE, 4, DEFAULT},
    {"fchmodat", INT, STRING, SIZE_T, NONE, NONE, NONE, 3, DEFAULT},
    {"faccessat", INT, STRING, SIZE_T, NONE, NONE, NONE, 3, DEFAULT},
    {"pselect6", INT, POINTER, POINTER, POINTER, DEFAULT, POINTER, 6, DEFAULT},
    {"ppoll", DEFAULT, SIZE_T, DEFAULT, POINTER, SIZE_T, NONE, 5, DEFAULT},
    {"unshare", SIZE_T, NONE, NONE, NONE, NONE, NONE, 1, DEFAULT},
    {"set_robust_list", DEFAULT, SIZE_T, NONE, NONE, NONE, NONE, 2, DEFAULT},
    {"get_robust_list", INT, DEFAULT, POINTER, NONE, NONE, NONE, 3, DEFAULT},
    {"splice", INT, POINTER, INT, POINTER, SIZE_T, SIZE_T, 6, DEFAULT},
    {"tee", INT, INT, SIZE_T, SIZE_T, NONE, NONE, 4, DEFAULT},
    {"sync_file_range", LONG, SIZE_T, SIZE_T, LONG, NONE, NONE, 4, DEFAULT},
    {"vmsplice", INT, DEFAULT, INT, SIZE_T, NONE, NONE, 4, DEFAULT},
    {"move_pages", SIZE_T, INT, DEFAULT, POINTER, POINTER, INT, 6, DEFAULT},
    {"utimensat", INT, STRING, DEFAULT, INT, NONE, NONE, 4, DEFAULT},
    {"epoll_pwait", INT, DEFAULT, INT, INT, POINTER, SIZE_T, 6, DEFAULT},
    {"signalfd", INT, POINTER, SIZE_T, NONE, NONE, NONE, 3, DEFAULT},
    {"timerfd_create", INT, INT, NONE, NONE, NONE, NONE, 2, DEFAULT},
    {"eventfd", SIZE_T, NONE, NONE, NONE, NONE, NONE, 1, DEFAULT},
    {"fallocate", LONG, LONG, SIZE_T, SIZE_T, NONE, NONE, 4, DEFAULT},
    {"timerfd_settime", INT, INT, DEFAULT, DEFAULT, NONE, NONE, 4, DEFAULT},
    {"timerfd_gettime", INT, DEFAULT, NONE, NONE, NONE, NONE, 2, DEFAULT},
    {"accept4", INT, DEFAULT, POINTER, INT, NONE, NONE, 4, DEFAULT},
    {"signalfd4", INT, DEFAULT, INT, INT, NONE, NONE, 4, DEFAULT},
    {"eventfd2", SIZE_T, INT, NONE, NONE, NONE, NONE, 2, DEFAULT},
    {"epoll_create1", INT, NONE, NONE, NONE, NONE, NONE, 1, DEFAULT},
    {"dup3", SIZE_T, SIZE_T, INT, NONE, NONE, NONE, 3, DEFAULT},
    {"pipe2", POINTER, INT, NONE, NONE, NONE, NONE, 2, DEFAULT},
    {"inotify_init1", INT, NONE, NONE, NONE, NONE, NONE, 1, DEFAULT},
    {"preadv", INT, DEFAULT, INT,
        INT, INT, NONE, 5, DEFAULT},
    {"pwritev", INT, DEFAULT, INT,
        INT, INT, NONE, 5, DEFAULT},
    {"rt_tgsigqueueinfo", SIZE_T, SIZE_T, INT, POINTER, NONE, NONE, 4, DEFAULT},
    {"perf_event_open", DEFAULT, SIZE_T, INT, INT, INT, NONE, 5, DEFAULT},
    {"recvmmsg", INT, DEFAULT, SIZE_T, SIZE_T, DEFAULT, NONE, 5, DEFAULT},
    {"fanotify_init", SIZE_T, SIZE_T, NONE, NONE, NONE, NONE, 2, DEFAULT},
    {"fanotify_mark", LONG, LONG, SIZE_T, LONG, LONG, NONE, 5, DEFAULT},
    {"prlimit64", SIZE_T, SIZE_T, DEFAULT, DEFAULT, NONE, NONE, 4, DEFAULT},
    {"name_to_handle_at", INT, STRING, DEFAULT, POINTER, INT, NONE, 5, DEFAULT},
    {"open_by_handle_at", INT, STRING, DEFAULT, POINTER, INT, NONE, 5, DEFAULT},
    {"clock_adjtime", SIZE_T, DEFAULT, NONE, NONE, NONE, NONE, 2, DEFAULT},
    {"syncfs", INT, NONE, NONE, NONE, NONE, NONE, 1, DEFAULT},
    {"sendmmsg", INT, DEFAULT, SIZE_T, SIZE_T, NONE, NONE, 4, DEFAULT},
    {"setns", INT, INT, NONE, NONE, NONE, NONE, 2, DEFAULT},
    {"getcpu", POINTER, POINTER, DEFAULT, NONE, NONE, NONE, 3, DEFAULT},
    {"process_vm_readv", SIZE_T, DEFAULT, INT,
        DEFAULT, INT, INT, 6, DEFAULT},
    {"process_vm_writev", SIZE_T, DEFAULT, INT,
        DEFAULT, INT, INT, 6, DEFAULT},
    {"kcmp", SIZE_T, SIZE_T, INT, INT, INT, NONE, 5, DEFAULT},
    {"finit_module", INT, STRING, INT, NONE, NONE, NONE, 3, DEFAULT},
    {"sched_setattr", SIZE_T, DEFAULT, SIZE_T, NONE, NONE, NONE, 3, DEFAULT},
    {"sched_getattr", SIZE_T, DEFAULT, SIZE_T, SIZE_T, NONE, NONE, 4, DEFAULT},
    {"renameat2", INT, STRING, INT, STRING, SIZE_T, NONE, 5, DEFAULT},
    {"seccomp", SIZE_T, SIZE_T, STRING, NONE, NONE, NONE, 3, DEFAULT},
    {"getrandom", STRING, SIZE_T, SIZE_T, NONE, NONE, NONE, 3, DEFAULT},
    {"memfd_create", STRING, SIZE_T, NONE, NONE, NONE, NONE, 2, DEFAULT},
    {"kexec_file_load", INT, INT, INT, STRING, INT, NONE, 5, DEFAULT},
    {"bpf", INT, POINTER, SIZE_T, NONE, NONE, NONE, 3, DEFAULT},
    {"execveat", INT, STRING, POINTER, POINTER, INT, NONE, 5, DEFAULT},
    {"userfaultfd", INT, NONE, NONE, NONE, NONE, NONE, 1, DEFAULT},
    {"membarrier", INT, INT, NONE, NONE, NONE, NONE, 2, DEFAULT},
    {"mlock2", INT, SIZE_T, INT, NONE, NONE, NONE, 3, DEFAULT},
    {"copy_file_range", INT, POINTER, INT,
        POINTER, SIZE_T, SIZE_T, 6, DEFAULT},
    {"preadv2", INT, DEFAULT, INT,
        INT, INT , INT, 6, DEFAULT},
    {"pwritev2", INT, DEFAULT, INT,
        INT, INT, INT, 6, DEFAULT},
    {NULL, NONE, NONE, NONE, NONE, NONE, NONE, 0, DEFAULT},
};

#endif